// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectionType.proto

package com.kikkar.packet;

/**
 * Protobuf enum {@code com.kikkar.packet.ConnectionType}
 */
public enum ConnectionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UPLOAD = 0;</code>
   */
  UPLOAD(0),
  /**
   * <code>DOWNLOAD = 1;</code>
   */
  DOWNLOAD(1),
  /**
   * <code>BOTH = 2;</code>
   */
  BOTH(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UPLOAD = 0;</code>
   */
  public static final int UPLOAD_VALUE = 0;
  /**
   * <code>DOWNLOAD = 1;</code>
   */
  public static final int DOWNLOAD_VALUE = 1;
  /**
   * <code>BOTH = 2;</code>
   */
  public static final int BOTH_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConnectionType valueOf(int value) {
    return forNumber(value);
  }

  public static ConnectionType forNumber(int value) {
    switch (value) {
      case 0: return UPLOAD;
      case 1: return DOWNLOAD;
      case 2: return BOTH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConnectionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConnectionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConnectionType>() {
          public ConnectionType findValueByNumber(int number) {
            return ConnectionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.kikkar.packet.ConnectionTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ConnectionType[] VALUES = values();

  public static ConnectionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConnectionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.kikkar.packet.ConnectionType)
}

