// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HaveMessage.proto

package com.kikkar.packet;

public interface HaveMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.HaveMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 videoNum = 1;</code>
   */
  int getVideoNum();
}
