// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeepAliveMessage.proto

package com.kikkar.packet;

public interface KeepAliveMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.KeepAliveMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageId = 1;</code>
   */
  int getMessageId();
}
