// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketWrapper.proto

package com.kikkar.packet;

public interface PacketWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.PacketWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 packetId = 1;</code>
   */
  int getPacketId();

  /**
   * <code>.com.kikkar.packet.ControlMessage controlMessage = 2;</code>
   */
  boolean hasControlMessage();
  /**
   * <code>.com.kikkar.packet.ControlMessage controlMessage = 2;</code>
   */
  com.kikkar.packet.ControlMessage getControlMessage();
  /**
   * <code>.com.kikkar.packet.ControlMessage controlMessage = 2;</code>
   */
  com.kikkar.packet.ControlMessageOrBuilder getControlMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.HaveMessage haveMessage = 3;</code>
   */
  boolean hasHaveMessage();
  /**
   * <code>.com.kikkar.packet.HaveMessage haveMessage = 3;</code>
   */
  com.kikkar.packet.HaveMessage getHaveMessage();
  /**
   * <code>.com.kikkar.packet.HaveMessage haveMessage = 3;</code>
   */
  com.kikkar.packet.HaveMessageOrBuilder getHaveMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.KeepAliveMessage keepAliveMessage = 4;</code>
   */
  boolean hasKeepAliveMessage();
  /**
   * <code>.com.kikkar.packet.KeepAliveMessage keepAliveMessage = 4;</code>
   */
  com.kikkar.packet.KeepAliveMessage getKeepAliveMessage();
  /**
   * <code>.com.kikkar.packet.KeepAliveMessage keepAliveMessage = 4;</code>
   */
  com.kikkar.packet.KeepAliveMessageOrBuilder getKeepAliveMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.NotInterestedMessage notInterestedMessage = 5;</code>
   */
  boolean hasNotInterestedMessage();
  /**
   * <code>.com.kikkar.packet.NotInterestedMessage notInterestedMessage = 5;</code>
   */
  com.kikkar.packet.NotInterestedMessage getNotInterestedMessage();
  /**
   * <code>.com.kikkar.packet.NotInterestedMessage notInterestedMessage = 5;</code>
   */
  com.kikkar.packet.NotInterestedMessageOrBuilder getNotInterestedMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.PingMessage pingMessage = 6;</code>
   */
  boolean hasPingMessage();
  /**
   * <code>.com.kikkar.packet.PingMessage pingMessage = 6;</code>
   */
  com.kikkar.packet.PingMessage getPingMessage();
  /**
   * <code>.com.kikkar.packet.PingMessage pingMessage = 6;</code>
   */
  com.kikkar.packet.PingMessageOrBuilder getPingMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.PongMessage pongMessage = 7;</code>
   */
  boolean hasPongMessage();
  /**
   * <code>.com.kikkar.packet.PongMessage pongMessage = 7;</code>
   */
  com.kikkar.packet.PongMessage getPongMessage();
  /**
   * <code>.com.kikkar.packet.PongMessage pongMessage = 7;</code>
   */
  com.kikkar.packet.PongMessageOrBuilder getPongMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.RequestMessage requestMessage = 8;</code>
   */
  boolean hasRequestMessage();
  /**
   * <code>.com.kikkar.packet.RequestMessage requestMessage = 8;</code>
   */
  com.kikkar.packet.RequestMessage getRequestMessage();
  /**
   * <code>.com.kikkar.packet.RequestMessage requestMessage = 8;</code>
   */
  com.kikkar.packet.RequestMessageOrBuilder getRequestMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.RequestVideoMessage requestVideoMessage = 9;</code>
   */
  boolean hasRequestVideoMessage();
  /**
   * <code>.com.kikkar.packet.RequestVideoMessage requestVideoMessage = 9;</code>
   */
  com.kikkar.packet.RequestVideoMessage getRequestVideoMessage();
  /**
   * <code>.com.kikkar.packet.RequestVideoMessage requestVideoMessage = 9;</code>
   */
  com.kikkar.packet.RequestVideoMessageOrBuilder getRequestVideoMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.ResponseMessage responseMessage = 10;</code>
   */
  boolean hasResponseMessage();
  /**
   * <code>.com.kikkar.packet.ResponseMessage responseMessage = 10;</code>
   */
  com.kikkar.packet.ResponseMessage getResponseMessage();
  /**
   * <code>.com.kikkar.packet.ResponseMessage responseMessage = 10;</code>
   */
  com.kikkar.packet.ResponseMessageOrBuilder getResponseMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.ResponseVideoMessage responseVideoMessage = 11;</code>
   */
  boolean hasResponseVideoMessage();
  /**
   * <code>.com.kikkar.packet.ResponseVideoMessage responseVideoMessage = 11;</code>
   */
  com.kikkar.packet.ResponseVideoMessage getResponseVideoMessage();
  /**
   * <code>.com.kikkar.packet.ResponseVideoMessage responseVideoMessage = 11;</code>
   */
  com.kikkar.packet.ResponseVideoMessageOrBuilder getResponseVideoMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.TerminatedMessage terminatedMessage = 12;</code>
   */
  boolean hasTerminatedMessage();
  /**
   * <code>.com.kikkar.packet.TerminatedMessage terminatedMessage = 12;</code>
   */
  com.kikkar.packet.TerminatedMessage getTerminatedMessage();
  /**
   * <code>.com.kikkar.packet.TerminatedMessage terminatedMessage = 12;</code>
   */
  com.kikkar.packet.TerminatedMessageOrBuilder getTerminatedMessageOrBuilder();

  /**
   * <code>.com.kikkar.packet.VideoPacket videoPacket = 13;</code>
   */
  boolean hasVideoPacket();
  /**
   * <code>.com.kikkar.packet.VideoPacket videoPacket = 13;</code>
   */
  com.kikkar.packet.VideoPacket getVideoPacket();
  /**
   * <code>.com.kikkar.packet.VideoPacket videoPacket = 13;</code>
   */
  com.kikkar.packet.VideoPacketOrBuilder getVideoPacketOrBuilder();

  public com.kikkar.packet.PacketWrapper.MessageCase getMessageCase();
}
