// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketWrapper.proto

package com.kikkar.packet;

public final class PacketWrapperOuterClass {
  private PacketWrapperOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kikkar_packet_PacketWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kikkar_packet_PacketWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PacketWrapper.proto\022\021com.kikkar.packet" +
      "\032\024ControlMessage.proto\032\021HaveMessage.prot" +
      "o\032\026KeepAliveMessage.proto\032\032NotInterested" +
      "Message.proto\032\021PingMessage.proto\032\021PongMe" +
      "ssage.proto\032\024RequestMessage.proto\032\031Reque" +
      "stVideoMessage.proto\032\025ResponseMessage.pr" +
      "oto\032\032ResponseVideoMessage.proto\032\027Termina" +
      "tedMessage.proto\032\021VideoPacket.proto\"\236\006\n\r" +
      "PacketWrapper\022\020\n\010packetId\030\001 \001(\005\022;\n\016contr" +
      "olMessage\030\002 \001(\0132!.com.kikkar.packet.Cont" +
      "rolMessageH\000\0225\n\013haveMessage\030\003 \001(\0132\036.com." +
      "kikkar.packet.HaveMessageH\000\022?\n\020keepAlive" +
      "Message\030\004 \001(\0132#.com.kikkar.packet.KeepAl" +
      "iveMessageH\000\022G\n\024notInterestedMessage\030\005 \001" +
      "(\0132\'.com.kikkar.packet.NotInterestedMess" +
      "ageH\000\0225\n\013pingMessage\030\006 \001(\0132\036.com.kikkar." +
      "packet.PingMessageH\000\0225\n\013pongMessage\030\007 \001(" +
      "\0132\036.com.kikkar.packet.PongMessageH\000\022;\n\016r" +
      "equestMessage\030\010 \001(\0132!.com.kikkar.packet." +
      "RequestMessageH\000\022E\n\023requestVideoMessage\030" +
      "\t \001(\0132&.com.kikkar.packet.RequestVideoMe" +
      "ssageH\000\022=\n\017responseMessage\030\n \001(\0132\".com.k" +
      "ikkar.packet.ResponseMessageH\000\022G\n\024respon" +
      "seVideoMessage\030\013 \001(\0132\'.com.kikkar.packet" +
      ".ResponseVideoMessageH\000\022A\n\021terminatedMes" +
      "sage\030\014 \001(\0132$.com.kikkar.packet.Terminate" +
      "dMessageH\000\0225\n\013videoPacket\030\r \001(\0132\036.com.ki" +
      "kkar.packet.VideoPacketH\000B\t\n\007messageB\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kikkar.packet.ControlMessageOuterClass.getDescriptor(),
          com.kikkar.packet.HaveMessageOuterClass.getDescriptor(),
          com.kikkar.packet.KeepAliveMessageOuterClass.getDescriptor(),
          com.kikkar.packet.NotInterestedMessageOuterClass.getDescriptor(),
          com.kikkar.packet.PingMessageOuterClass.getDescriptor(),
          com.kikkar.packet.PongMessageOuterClass.getDescriptor(),
          com.kikkar.packet.RequestMessageOuterClass.getDescriptor(),
          com.kikkar.packet.RequestVideoMessageOuterClass.getDescriptor(),
          com.kikkar.packet.ResponseMessageOuterClass.getDescriptor(),
          com.kikkar.packet.ResponseVideoMessageOuterClass.getDescriptor(),
          com.kikkar.packet.TerminatedMessageOuterClass.getDescriptor(),
          com.kikkar.packet.VideoPacketOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_kikkar_packet_PacketWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kikkar_packet_PacketWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kikkar_packet_PacketWrapper_descriptor,
        new java.lang.String[] { "PacketId", "ControlMessage", "HaveMessage", "KeepAliveMessage", "NotInterestedMessage", "PingMessage", "PongMessage", "RequestMessage", "RequestVideoMessage", "ResponseMessage", "ResponseVideoMessage", "TerminatedMessage", "VideoPacket", "Message", });
    com.kikkar.packet.ControlMessageOuterClass.getDescriptor();
    com.kikkar.packet.HaveMessageOuterClass.getDescriptor();
    com.kikkar.packet.KeepAliveMessageOuterClass.getDescriptor();
    com.kikkar.packet.NotInterestedMessageOuterClass.getDescriptor();
    com.kikkar.packet.PingMessageOuterClass.getDescriptor();
    com.kikkar.packet.PongMessageOuterClass.getDescriptor();
    com.kikkar.packet.RequestMessageOuterClass.getDescriptor();
    com.kikkar.packet.RequestVideoMessageOuterClass.getDescriptor();
    com.kikkar.packet.ResponseMessageOuterClass.getDescriptor();
    com.kikkar.packet.ResponseVideoMessageOuterClass.getDescriptor();
    com.kikkar.packet.TerminatedMessageOuterClass.getDescriptor();
    com.kikkar.packet.VideoPacketOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
