// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PingMessage.proto

package com.kikkar.packet;

public interface PingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.PingMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pingId = 1;</code>
   */
  int getPingId();

  /**
   * <code>int32 clubNumber = 2;</code>
   */
  int getClubNumber();

  /**
   * <code>.com.kikkar.packet.ConnectionType connectionType = 3;</code>
   */
  int getConnectionTypeValue();
  /**
   * <code>.com.kikkar.packet.ConnectionType connectionType = 3;</code>
   */
  com.kikkar.packet.ConnectionType getConnectionType();
}
