// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PongMessage.proto

package com.kikkar.packet;

/**
 * Protobuf type {@code com.kikkar.packet.PongMessage}
 */
public  final class PongMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kikkar.packet.PongMessage)
    PongMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PongMessage.newBuilder() to construct.
  private PongMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PongMessage() {
    responsePingId_ = 0;
    uploadLinkNum_ = 0;
    downloadLinkNum_ = 0;
    bufferVideoNum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PongMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            responsePingId_ = input.readInt32();
            break;
          }
          case 16: {

            uploadLinkNum_ = input.readInt32();
            break;
          }
          case 24: {

            downloadLinkNum_ = input.readInt32();
            break;
          }
          case 32: {

            bufferVideoNum_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kikkar.packet.PongMessageOuterClass.internal_static_com_kikkar_packet_PongMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kikkar.packet.PongMessageOuterClass.internal_static_com_kikkar_packet_PongMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kikkar.packet.PongMessage.class, com.kikkar.packet.PongMessage.Builder.class);
  }

  public static final int RESPONSEPINGID_FIELD_NUMBER = 1;
  private int responsePingId_;
  /**
   * <code>int32 responsePingId = 1;</code>
   */
  public int getResponsePingId() {
    return responsePingId_;
  }

  public static final int UPLOADLINKNUM_FIELD_NUMBER = 2;
  private int uploadLinkNum_;
  /**
   * <code>int32 uploadLinkNum = 2;</code>
   */
  public int getUploadLinkNum() {
    return uploadLinkNum_;
  }

  public static final int DOWNLOADLINKNUM_FIELD_NUMBER = 3;
  private int downloadLinkNum_;
  /**
   * <code>int32 downloadLinkNum = 3;</code>
   */
  public int getDownloadLinkNum() {
    return downloadLinkNum_;
  }

  public static final int BUFFERVIDEONUM_FIELD_NUMBER = 4;
  private int bufferVideoNum_;
  /**
   * <code>int32 bufferVideoNum = 4;</code>
   */
  public int getBufferVideoNum() {
    return bufferVideoNum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responsePingId_ != 0) {
      output.writeInt32(1, responsePingId_);
    }
    if (uploadLinkNum_ != 0) {
      output.writeInt32(2, uploadLinkNum_);
    }
    if (downloadLinkNum_ != 0) {
      output.writeInt32(3, downloadLinkNum_);
    }
    if (bufferVideoNum_ != 0) {
      output.writeInt32(4, bufferVideoNum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responsePingId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, responsePingId_);
    }
    if (uploadLinkNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, uploadLinkNum_);
    }
    if (downloadLinkNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, downloadLinkNum_);
    }
    if (bufferVideoNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, bufferVideoNum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kikkar.packet.PongMessage)) {
      return super.equals(obj);
    }
    com.kikkar.packet.PongMessage other = (com.kikkar.packet.PongMessage) obj;

    boolean result = true;
    result = result && (getResponsePingId()
        == other.getResponsePingId());
    result = result && (getUploadLinkNum()
        == other.getUploadLinkNum());
    result = result && (getDownloadLinkNum()
        == other.getDownloadLinkNum());
    result = result && (getBufferVideoNum()
        == other.getBufferVideoNum());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSEPINGID_FIELD_NUMBER;
    hash = (53 * hash) + getResponsePingId();
    hash = (37 * hash) + UPLOADLINKNUM_FIELD_NUMBER;
    hash = (53 * hash) + getUploadLinkNum();
    hash = (37 * hash) + DOWNLOADLINKNUM_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadLinkNum();
    hash = (37 * hash) + BUFFERVIDEONUM_FIELD_NUMBER;
    hash = (53 * hash) + getBufferVideoNum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kikkar.packet.PongMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.PongMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.PongMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kikkar.packet.PongMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.PongMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.PongMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kikkar.packet.PongMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kikkar.packet.PongMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kikkar.packet.PongMessage)
      com.kikkar.packet.PongMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kikkar.packet.PongMessageOuterClass.internal_static_com_kikkar_packet_PongMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kikkar.packet.PongMessageOuterClass.internal_static_com_kikkar_packet_PongMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kikkar.packet.PongMessage.class, com.kikkar.packet.PongMessage.Builder.class);
    }

    // Construct using com.kikkar.packet.PongMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responsePingId_ = 0;

      uploadLinkNum_ = 0;

      downloadLinkNum_ = 0;

      bufferVideoNum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kikkar.packet.PongMessageOuterClass.internal_static_com_kikkar_packet_PongMessage_descriptor;
    }

    @java.lang.Override
    public com.kikkar.packet.PongMessage getDefaultInstanceForType() {
      return com.kikkar.packet.PongMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.kikkar.packet.PongMessage build() {
      com.kikkar.packet.PongMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kikkar.packet.PongMessage buildPartial() {
      com.kikkar.packet.PongMessage result = new com.kikkar.packet.PongMessage(this);
      result.responsePingId_ = responsePingId_;
      result.uploadLinkNum_ = uploadLinkNum_;
      result.downloadLinkNum_ = downloadLinkNum_;
      result.bufferVideoNum_ = bufferVideoNum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kikkar.packet.PongMessage) {
        return mergeFrom((com.kikkar.packet.PongMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kikkar.packet.PongMessage other) {
      if (other == com.kikkar.packet.PongMessage.getDefaultInstance()) return this;
      if (other.getResponsePingId() != 0) {
        setResponsePingId(other.getResponsePingId());
      }
      if (other.getUploadLinkNum() != 0) {
        setUploadLinkNum(other.getUploadLinkNum());
      }
      if (other.getDownloadLinkNum() != 0) {
        setDownloadLinkNum(other.getDownloadLinkNum());
      }
      if (other.getBufferVideoNum() != 0) {
        setBufferVideoNum(other.getBufferVideoNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kikkar.packet.PongMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kikkar.packet.PongMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int responsePingId_ ;
    /**
     * <code>int32 responsePingId = 1;</code>
     */
    public int getResponsePingId() {
      return responsePingId_;
    }
    /**
     * <code>int32 responsePingId = 1;</code>
     */
    public Builder setResponsePingId(int value) {
      
      responsePingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responsePingId = 1;</code>
     */
    public Builder clearResponsePingId() {
      
      responsePingId_ = 0;
      onChanged();
      return this;
    }

    private int uploadLinkNum_ ;
    /**
     * <code>int32 uploadLinkNum = 2;</code>
     */
    public int getUploadLinkNum() {
      return uploadLinkNum_;
    }
    /**
     * <code>int32 uploadLinkNum = 2;</code>
     */
    public Builder setUploadLinkNum(int value) {
      
      uploadLinkNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uploadLinkNum = 2;</code>
     */
    public Builder clearUploadLinkNum() {
      
      uploadLinkNum_ = 0;
      onChanged();
      return this;
    }

    private int downloadLinkNum_ ;
    /**
     * <code>int32 downloadLinkNum = 3;</code>
     */
    public int getDownloadLinkNum() {
      return downloadLinkNum_;
    }
    /**
     * <code>int32 downloadLinkNum = 3;</code>
     */
    public Builder setDownloadLinkNum(int value) {
      
      downloadLinkNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 downloadLinkNum = 3;</code>
     */
    public Builder clearDownloadLinkNum() {
      
      downloadLinkNum_ = 0;
      onChanged();
      return this;
    }

    private int bufferVideoNum_ ;
    /**
     * <code>int32 bufferVideoNum = 4;</code>
     */
    public int getBufferVideoNum() {
      return bufferVideoNum_;
    }
    /**
     * <code>int32 bufferVideoNum = 4;</code>
     */
    public Builder setBufferVideoNum(int value) {
      
      bufferVideoNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bufferVideoNum = 4;</code>
     */
    public Builder clearBufferVideoNum() {
      
      bufferVideoNum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kikkar.packet.PongMessage)
  }

  // @@protoc_insertion_point(class_scope:com.kikkar.packet.PongMessage)
  private static final com.kikkar.packet.PongMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kikkar.packet.PongMessage();
  }

  public static com.kikkar.packet.PongMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PongMessage>
      PARSER = new com.google.protobuf.AbstractParser<PongMessage>() {
    @java.lang.Override
    public PongMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PongMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PongMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PongMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kikkar.packet.PongMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

