// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVideoMessage.proto

package com.kikkar.packet;

public interface RequestVideoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.RequestVideoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageId = 1;</code>
   */
  int getMessageId();

  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  java.util.List<java.lang.Integer> getVideoNumList();
  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  int getVideoNumCount();
  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  int getVideoNum(int index);
}
