// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVideoMessage.proto

package com.kikkar.packet;

public interface RequestVideoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.RequestVideoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageId = 1;</code>
   */
  int getMessageId();

  /**
   * <code>int32 videoNum = 2;</code>
   */
  int getVideoNum();
}
