// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestMessage.proto

package com.kikkar.packet;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestId = 1;</code>
   */
  int getRequestId();

  /**
   * <code>int32 clubNumber = 2;</code>
   */
  int getClubNumber();

  /**
   * <code>.com.kikkar.packet.ConnectionType connectionType = 3;</code>
   */
  int getConnectionTypeValue();
  /**
   * <code>.com.kikkar.packet.ConnectionType connectionType = 3;</code>
   */
  com.kikkar.packet.ConnectionType getConnectionType();
}
