// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseVideoMessage.proto

package com.kikkar.packet;

public interface ResponseVideoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.ResponseVideoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestMessageId = 1;</code>
   */
  int getRequestMessageId();

  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  java.util.List<java.lang.Integer> getVideoNumList();
  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  int getVideoNumCount();
  /**
   * <code>repeated int32 videoNum = 2 [packed = true];</code>
   */
  int getVideoNum(int index);
}
