// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseMessage.proto

package com.kikkar.packet;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responseRequestId = 1;</code>
   */
  int getResponseRequestId();
}
