// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseVideoMessage.proto

package com.kikkar.packet;

public interface ResponseVideoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.ResponseVideoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 videoNum = 1;</code>
   */
  int getVideoNum();

  /**
   * <code>int32 chunkNum = 2;</code>
   */
  int getChunkNum();

  /**
   * <code>bytes video = 3;</code>
   */
  com.google.protobuf.ByteString getVideo();
}
