// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminatedReason.proto

package com.kikkar.packet;

/**
 * Protobuf enum {@code com.kikkar.packet.TerminatedReason}
 */
public enum TerminatedReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LEAVE_PROGRAM = 0;</code>
   */
  LEAVE_PROGRAM(0),
  /**
   * <code>BLOCK_TIMEOUT = 1;</code>
   */
  BLOCK_TIMEOUT(1),
  /**
   * <code>PACKET_NUMBER_DISORDER = 2;</code>
   */
  PACKET_NUMBER_DISORDER(2),
  /**
   * <code>DEAD_PEER = 3;</code>
   */
  DEAD_PEER(3),
  /**
   * <code>NEW_CONNECTION = 4;</code>
   */
  NEW_CONNECTION(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LEAVE_PROGRAM = 0;</code>
   */
  public static final int LEAVE_PROGRAM_VALUE = 0;
  /**
   * <code>BLOCK_TIMEOUT = 1;</code>
   */
  public static final int BLOCK_TIMEOUT_VALUE = 1;
  /**
   * <code>PACKET_NUMBER_DISORDER = 2;</code>
   */
  public static final int PACKET_NUMBER_DISORDER_VALUE = 2;
  /**
   * <code>DEAD_PEER = 3;</code>
   */
  public static final int DEAD_PEER_VALUE = 3;
  /**
   * <code>NEW_CONNECTION = 4;</code>
   */
  public static final int NEW_CONNECTION_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TerminatedReason valueOf(int value) {
    return forNumber(value);
  }

  public static TerminatedReason forNumber(int value) {
    switch (value) {
      case 0: return LEAVE_PROGRAM;
      case 1: return BLOCK_TIMEOUT;
      case 2: return PACKET_NUMBER_DISORDER;
      case 3: return DEAD_PEER;
      case 4: return NEW_CONNECTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TerminatedReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TerminatedReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TerminatedReason>() {
          public TerminatedReason findValueByNumber(int number) {
            return TerminatedReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.kikkar.packet.TerminatedReasonOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final TerminatedReason[] VALUES = values();

  public static TerminatedReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TerminatedReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.kikkar.packet.TerminatedReason)
}

