// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminatedMessage.proto

package com.kikkar.packet;

public interface TerminatedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.TerminatedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 terminatedId = 1;</code>
   */
  int getTerminatedId();

  /**
   * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
   */
  int getTerminatedReasonValue();
  /**
   * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
   */
  com.kikkar.packet.TerminatedReason getTerminatedReason();
}
