// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminatedMessage.proto

package com.kikkar.packet;

public final class TerminatedMessageOuterClass {
  private TerminatedMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kikkar_packet_TerminatedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kikkar_packet_TerminatedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TerminatedMessage.proto\022\021com.kikkar.pa" +
      "cket\032\026TerminatedReason.proto\"h\n\021Terminat" +
      "edMessage\022\024\n\014terminatedId\030\001 \001(\005\022=\n\020termi" +
      "natedReason\030\002 \001(\0162#.com.kikkar.packet.Te" +
      "rminatedReasonB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kikkar.packet.TerminatedReasonOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_kikkar_packet_TerminatedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kikkar_packet_TerminatedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kikkar_packet_TerminatedMessage_descriptor,
        new java.lang.String[] { "TerminatedId", "TerminatedReason", });
    com.kikkar.packet.TerminatedReasonOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
