// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminatedMessage.proto

package com.kikkar.packet;

/**
 * Protobuf type {@code com.kikkar.packet.TerminatedMessage}
 */
public  final class TerminatedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kikkar.packet.TerminatedMessage)
    TerminatedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TerminatedMessage.newBuilder() to construct.
  private TerminatedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TerminatedMessage() {
    terminatedId_ = 0;
    terminatedReason_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TerminatedMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            terminatedId_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            terminatedReason_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kikkar.packet.TerminatedMessageOuterClass.internal_static_com_kikkar_packet_TerminatedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kikkar.packet.TerminatedMessageOuterClass.internal_static_com_kikkar_packet_TerminatedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kikkar.packet.TerminatedMessage.class, com.kikkar.packet.TerminatedMessage.Builder.class);
  }

  public static final int TERMINATEDID_FIELD_NUMBER = 1;
  private int terminatedId_;
  /**
   * <code>int32 terminatedId = 1;</code>
   */
  public int getTerminatedId() {
    return terminatedId_;
  }

  public static final int TERMINATEDREASON_FIELD_NUMBER = 2;
  private int terminatedReason_;
  /**
   * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
   */
  public int getTerminatedReasonValue() {
    return terminatedReason_;
  }
  /**
   * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
   */
  public com.kikkar.packet.TerminatedReason getTerminatedReason() {
    @SuppressWarnings("deprecation")
    com.kikkar.packet.TerminatedReason result = com.kikkar.packet.TerminatedReason.valueOf(terminatedReason_);
    return result == null ? com.kikkar.packet.TerminatedReason.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (terminatedId_ != 0) {
      output.writeInt32(1, terminatedId_);
    }
    if (terminatedReason_ != com.kikkar.packet.TerminatedReason.LEAVE_PROGRAM.getNumber()) {
      output.writeEnum(2, terminatedReason_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (terminatedId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, terminatedId_);
    }
    if (terminatedReason_ != com.kikkar.packet.TerminatedReason.LEAVE_PROGRAM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, terminatedReason_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kikkar.packet.TerminatedMessage)) {
      return super.equals(obj);
    }
    com.kikkar.packet.TerminatedMessage other = (com.kikkar.packet.TerminatedMessage) obj;

    boolean result = true;
    result = result && (getTerminatedId()
        == other.getTerminatedId());
    result = result && terminatedReason_ == other.terminatedReason_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERMINATEDID_FIELD_NUMBER;
    hash = (53 * hash) + getTerminatedId();
    hash = (37 * hash) + TERMINATEDREASON_FIELD_NUMBER;
    hash = (53 * hash) + terminatedReason_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kikkar.packet.TerminatedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kikkar.packet.TerminatedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.TerminatedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kikkar.packet.TerminatedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kikkar.packet.TerminatedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kikkar.packet.TerminatedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kikkar.packet.TerminatedMessage)
      com.kikkar.packet.TerminatedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kikkar.packet.TerminatedMessageOuterClass.internal_static_com_kikkar_packet_TerminatedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kikkar.packet.TerminatedMessageOuterClass.internal_static_com_kikkar_packet_TerminatedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kikkar.packet.TerminatedMessage.class, com.kikkar.packet.TerminatedMessage.Builder.class);
    }

    // Construct using com.kikkar.packet.TerminatedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      terminatedId_ = 0;

      terminatedReason_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kikkar.packet.TerminatedMessageOuterClass.internal_static_com_kikkar_packet_TerminatedMessage_descriptor;
    }

    @java.lang.Override
    public com.kikkar.packet.TerminatedMessage getDefaultInstanceForType() {
      return com.kikkar.packet.TerminatedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.kikkar.packet.TerminatedMessage build() {
      com.kikkar.packet.TerminatedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kikkar.packet.TerminatedMessage buildPartial() {
      com.kikkar.packet.TerminatedMessage result = new com.kikkar.packet.TerminatedMessage(this);
      result.terminatedId_ = terminatedId_;
      result.terminatedReason_ = terminatedReason_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kikkar.packet.TerminatedMessage) {
        return mergeFrom((com.kikkar.packet.TerminatedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kikkar.packet.TerminatedMessage other) {
      if (other == com.kikkar.packet.TerminatedMessage.getDefaultInstance()) return this;
      if (other.getTerminatedId() != 0) {
        setTerminatedId(other.getTerminatedId());
      }
      if (other.terminatedReason_ != 0) {
        setTerminatedReasonValue(other.getTerminatedReasonValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kikkar.packet.TerminatedMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kikkar.packet.TerminatedMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int terminatedId_ ;
    /**
     * <code>int32 terminatedId = 1;</code>
     */
    public int getTerminatedId() {
      return terminatedId_;
    }
    /**
     * <code>int32 terminatedId = 1;</code>
     */
    public Builder setTerminatedId(int value) {
      
      terminatedId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 terminatedId = 1;</code>
     */
    public Builder clearTerminatedId() {
      
      terminatedId_ = 0;
      onChanged();
      return this;
    }

    private int terminatedReason_ = 0;
    /**
     * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
     */
    public int getTerminatedReasonValue() {
      return terminatedReason_;
    }
    /**
     * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
     */
    public Builder setTerminatedReasonValue(int value) {
      terminatedReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
     */
    public com.kikkar.packet.TerminatedReason getTerminatedReason() {
      @SuppressWarnings("deprecation")
      com.kikkar.packet.TerminatedReason result = com.kikkar.packet.TerminatedReason.valueOf(terminatedReason_);
      return result == null ? com.kikkar.packet.TerminatedReason.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
     */
    public Builder setTerminatedReason(com.kikkar.packet.TerminatedReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      terminatedReason_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.kikkar.packet.TerminatedReason terminatedReason = 2;</code>
     */
    public Builder clearTerminatedReason() {
      
      terminatedReason_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kikkar.packet.TerminatedMessage)
  }

  // @@protoc_insertion_point(class_scope:com.kikkar.packet.TerminatedMessage)
  private static final com.kikkar.packet.TerminatedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kikkar.packet.TerminatedMessage();
  }

  public static com.kikkar.packet.TerminatedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TerminatedMessage>
      PARSER = new com.google.protobuf.AbstractParser<TerminatedMessage>() {
    @java.lang.Override
    public TerminatedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TerminatedMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TerminatedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TerminatedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kikkar.packet.TerminatedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

