// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoPacket.proto

package com.kikkar.packet;

public interface VideoPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kikkar.packet.VideoPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 videoNum = 1;</code>
   */
  int getVideoNum();

  /**
   * <code>int32 chunkNum = 2;</code>
   */
  int getChunkNum();

  /**
   * <code>bool firstFrame = 3;</code>
   */
  boolean getFirstFrame();

  /**
   * <code>bytes video = 4;</code>
   */
  com.google.protobuf.ByteString getVideo();
}
