// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoPacket.proto

package com.kikkar.packet;

public final class VideoPacketOuterClass {
  private VideoPacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kikkar_packet_VideoPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kikkar_packet_VideoPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021VideoPacket.proto\022\021com.kikkar.packet\"T" +
      "\n\013VideoPacket\022\020\n\010videoNum\030\001 \001(\005\022\020\n\010chunk" +
      "Num\030\002 \001(\005\022\022\n\nfirstFrame\030\003 \001(\010\022\r\n\005video\030\004" +
      " \001(\014B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kikkar_packet_VideoPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kikkar_packet_VideoPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kikkar_packet_VideoPacket_descriptor,
        new java.lang.String[] { "VideoNum", "ChunkNum", "FirstFrame", "Video", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
